# How to deploy:
# gcloud app deploy app.yaml

service: admindashboard
runtime: nodejs16

# Force https and redirect http to https
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# Environment variables that need to be exposed to the client (with NEXT_PUBLIC_) should be added at build time
build_env_variables:
  NEXT_PUBLIC_WRA_DASHBOARD_API_URL: "https://www-dashboard-api-dot-deft-stratum-290216.uc.r.appspot.com/api/v1"
