# How to deploy:
# gcloud app deploy app.yaml

service: admindashboard
runtime: nodejs18

# Force https and redirect http to https
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# Environment variables that need to be exposed to the client (with NEXT_PUBLIC_) should be added at build time
# For manual deployment, replace the variables starting with $ with your own values
build_env_variables:
  # Required
  NEXT_PUBLIC_DASHBOARD_API_URL: $NEXT_PUBLIC_DASHBOARD_API_URL

  # These env variables can be ignored
  NEXT_PUBLIC_PMNCH_DASHBOARD_API_URL: $NEXT_PUBLIC_PMNCH_DASHBOARD_API_URL
